name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc unzip wget zip gcc-avr git python3-pip binutils-avr avr-libc dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
    - name: Update QMK Firmware
      run: |
        git submodule update --init
        cd qmk_firmware && make git-submodule && python3 -m pip install --user qmk && qmk setup

    - name: Link custom keymap definition
      run: ln -s $(pwd)/keyball $(pwd)/qmk_firmware/keyboards/keyball
    - name: Build firmware hex distribution
      run: cd qmk_firmware && make qmk compile -j 4 -kb keyball/keyball46 -km j1n6
      
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: keyball_keyball46_j1n6.hex
        path: qmk_firmware/keyball_keyball46_j1n6.hex
    
    - name: Release
      uses: docker://softprops/action-gh-release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: qmk_firmware/keyball_keyball46_j1n6.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
